# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '15d908fe-b0b6-4cff-8200-85265010d5e9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-shimu-cicd'
    location: 'Japan East'
    templateLocation: 'URL of the file'
    overrideParameters: '-projectName shimu'
    csmFileLink: 'https://raw.githubusercontent.com/testkenji-shimura/test/main/create_web_app/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

